services:
  waha:
    image: docker.1ms.run/atendai/evolution-api:latest # Evolution API for WhatsApp
    container_name: waha-multisession
    restart: unless-stopped
    ports:
      # Evolution API default port is 8080
      - "127.0.0.1:8000:8080" 
    volumes:
      # This is crucial for persisting your session data
      - ./.sessions:/app/.sessions
    environment:
      # --- Recommended Engine for Notifications ---
      - WHATSAPP_DEFAULT_ENGINE=GOWS
      - WHATSAPP_RESTART_ALL_SESSIONS=true
      
      # --- Security (IMPORTANT for deployment) ---
      # Generate a secure key for production. 'admin' is for local testing only.
      - WAHA_API_KEY=admin 
      
      # --- Optional: Dashboard and Swagger credentials ---
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=admin
